# Generated by Django 4.2.4 on 2023-09-01 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLivraria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('preco', models.FloatField()),
                ('livraria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livraria')),
            ],
        ),
    ]
